# nazwa programu:
#PROG = zad01
PROG = zad02
#PROG = zad03

# biblioteki:
LIBS = -lGL -lGLU -lglut -lm

$(PROG) : $(PROG).c
	gcc -Wall -std=c99 -D_GNU_SOURCE $(PROG).c -o $(PROG) $(LIBS)

usun :
	rm -f $(PROG) *~
